### ISSUE TITLE
Awards Page Uniformity

### ISSUE THREAD

**Issue by Lev1ty** [the-reckoner/reckoner-site#11]
- Let's make every single awards page the same formatting (within the wreaths). Base it on the 5th guard format.
- As well, the previous awards pages aren't formatted into rows like the 5th guard page is and displays awkwardly on small screens. Please conform them to what you've done with the 5th guard page.
![screenshot from 2018-02-18 13-31-45](https://user-images.githubusercontent.com/15148828/36355396-8bd5906e-14b0-11e8-8251-3dea6a268cc6.png)
![screenshot from 2018-02-18 13-31-59](https://user-images.githubusercontent.com/15148828/36355395-8bc9586c-14b0-11e8-8932-deea770df251.png)

**Comment by jenniferzliang** [comment]
Where can I find the awards for the 6th guard?

**Comment by Lev1ty** [comment]
@torvarun
